# Generated by Django 5.1 on 2025-04-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(default='hola'),
        ),
    ]
